### ISSUE TITLE
Pickle failure

### ISSUE THREAD

**Issue by da4089** [geophile/marcel#4] opened 2020-06-01 07:38 UTC
So, trying to run anything in Marcel appears to cause the following error:

>  laptop> marcel 
$ print('a')
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/main.py", line 209, in <module>
    MAIN.run()
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/main.py", line 116, in run
    self.run_command(line)
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/main.py", line 137, in run_command
    self.job_control.create_job(command)
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/job.py", line 235, in create_job
    job = Job(self.env, command)
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/job.py", line 77, in __init__
    self.start_process()
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/job.py", line 168, in start_process
    self.process.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Job.start_process.<locals>.run_command'
laptop> 

I'm not sure where to start debugging that.  Any hints?

macOS 10.14.6  /  Python 3.8.2

**Comment by geophile** [comment] 2020-06-01 13:54
Very odd. This works for me, on both Linux and MacOS. I will look at the stack dump in detail and try to figure out what's going on. I see this:

M-0.7.8 jao@cheese:~$ print('a')
printa

However, I should point out that while print('a') "works" for me, it may not do what you intended. It does not write 'a' to stdout. Marcel is not a REPL,so it does not accept arbitrary Python. The language it does accept is defined by the marcel grammar (see parser.py), and in that grammar, parentheses can be used to delimit Python functions. print('a') is the string "print" followed by the parenthesized expression ('a') which evaluates to "a". These are not separated by whitespace, so it looks like one token, printa, which is what I see. 

Note that "print ('a')" with a space following print, would call the executable named print, passing "a" to it, (that results from evaluting the function ('a')). On Linux at least, this produces no output.

To run the Python print, you could have done this: (print('a')) which produces this output:

M-0.7.8 jao@cheese:~$ (print('a'))
a
None

The 'a' comes from Python printing "a", and the None comes from the result of the print function returning and passing None to stdout. Note that this syntax, (print('a')) is shorthand for:

map (lambda: print('a'))

I.e., you are actually invoking the map operator to a function with no parameters, which calls print('a'). Marcel allows you to omit the "lambda" from functions, and also to omit "map" if it is the first thing in the pipeline.

I still don't understand why you are seeing a pickling problem though. Will look at it.

**Comment by geophile** [comment] 2020-06-01 14:02
1) I assume you have dill installed (especially following your setup suggestion).
2) My Mac is running Catalina, 10.15.something. I wonder if this is somehow a platform issue?

**Comment by geophile** [comment] 2020-06-01 17:56
I don't understand exactly what causes this failure, but I have some idea of what provoked it. I have committed a possible fix, and I'm wondering if it works for you, (0.7.9 on PyPi).

**Comment by da4089** [comment] 2020-06-01 21:26
Thanks Jack!  I'll have a look at that this morning and report back.

**Comment by da4089** [comment] 2020-06-01 22:31
Ok.  Installed update:

> (venv38) laptop > pip install marcel
Requirement already satisfied: marcel in ./venv38/lib/python3.8/site-packages (0.7.9)
Requirement already satisfied: dill in ./venv38/lib/python3.8/site-packages (from marcel) (0.3.1.1)
(venv38) laptop > 

Different result this time ...

> $ (print('a'))
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/main.py", line 209, in <module>
    MAIN.run()
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/main.py", line 116, in run
    self.run_command(line)
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/main.py", line 137, in run_command
    self.job_control.create_job(command)
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/job.py", line 235, in create_job
    job = Job(self.env, command)
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/job.py", line 77, in __init__
    self.start_process()
  File "/Users/d/work/third-party/marcel-play/venv38/lib/python3.8/site-packages/marcel/job.py", line 154, in start_process
    self.process.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'setquit.<locals>.Quitter'
(venv38) laptop >

**Comment by geophile** [comment] 2020-06-01 22:43
That's a similar result -- a pickling error from the multiprocessing module, but this time on a different object. The multiprocessing module can spawn processes in a number of ways, with one difference being reliance on pickling. It looks like my two environments (Linux, MacOS Catalina) are using one approach while your environment is using a different one. I need to research this some more. It is possible that forcing the spawning approach will either fix the problem for you, or generate a different error. I'll let you know as I make progress.

For now, do you have a Linux environment you can use to try marcel?

**Comment by geophile** [comment] 2020-06-02 00:40
OK, try 0.7.10. The marcel script now takes a command-line flag --mpstart. Legal values are fork, spawn, and forkserver. I reproduced the failure using spawn, which appears to be the default for Mac as of Python 3.8. I think this explains the discrepancy between your Mac and mine. (I don't have my mac with me at the moment.)

I am particularly interested in seeing what happens when you try --mpstart fork.

**Comment by da4089** [comment] 2020-06-02 00:49
Yes, I have a couple of LInux options, so I'll check those out.

One thought re: why my environment might behave differently: I'm using Python 3.8 from MacPorts -- not the standard python.org binary -- so perhaps there's something different in how it's built?  I'll have a look at your recent change, and try to isolate a test case using multiprocessing directly, so I can narrow it down.

**Comment by da4089** [comment] 2020-06-02 01:00
Ok.  Installed update.

Using `--mpstart fork` works!  (yay!)  `--mpstart spawn`  and `--mpstart forkserver` both fail trying to pickle `run_command_in_child`

**Comment by geophile** [comment] 2020-06-02 02:53
Yes, that's what I'm seeing. I'll close this issue. Curious to hear about any other issue you run into, and and other feedback you have.

**Closed by geophile** 2020-06-02 02:53 UTC
